version: '3.8'

services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: capstoneDB_v2
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - my_network


  pg-admin:
    image: dpage/pgadmin4:6

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@dev.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    command: [ "start-dev" ]
    networks:
      - my_network

  
volumes:
  pg_data:
  redis_data:
  keycloak_data:

networks:
  my_network:
    driver: bridge
