
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5430/capstoneDB_v2
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
