

server:
  port: 8222

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://registry:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/book/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: bag-service
          uri: lb://bag-service
          predicates:
            - Path=/api/v1/bag/** , /api/v1/utility/**

