
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://registry:8761/eureka


server:
  port: 8092
spring:
  application:
    name: member-service
    config:
      bag-url: http://bag-service:8093/api/v1/**
      book-url: http://book-service:8090/api/v1/book

  datasource:
    url: jdbc:postgresql://postgres-db:5432/capstoneDB_v2
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/capstone
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


